_target_: src.models.lstm_module.LSTMLitModule
lr: 0.001
#weight_decay: 0.0005
weight_decay: 0

net:
  _target_: src.models.components.lstm.LSTM
  input_dim: 63
  latent_dim: 256
  num_layers: 4
  bidirectional: True
  n_time_steps: 101
