_target_: src.datamodules.sign_mfcc_datamodule.SignMFCCDataModule

poses_dir: ${data_dir}/train_poses # data_dir is specified in config.yaml
specto_dir: ${data_dir}/mfcc
batch_size: 64
train_val_test_split: [0.7, 0.2, 0.1] # In percentages
num_workers: 0
pin_memory: False
